# Generated by Django 3.0.7 on 2020-06-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=30)),
                ('title_main', models.CharField(max_length=100)),
                ('title_sub', models.CharField(max_length=100)),
            ],
        ),
    ]
